name: Main Workflow
on:
 push:
  branches: ['main']
 workflow_dispatch: 
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST2 }} # Usa la variable de entorno
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN2 }}       # Usa la variable de entorno

